<?php
/**
 * Copyright © Klarna Bank AB (publ)
 *
 * For the full copyright and license information, please view the NOTICE
 * and LICENSE files that were distributed with this source code.
 */

/** @var Klarna\Kec\Block\Product $block */
/** @var Magento\Framework\Escaper $escaper */
?>

<div id="klarna-kec-placeholder"></div>

<?php

if ($block->isShowable()): ?>
    <?php $authCallbackToken = $block->getAuthCallbackToken(false); ?>

    <script>

        window.klarnaAsyncCallback = function () {
            window.Klarna.Payments.Buttons.init({
                client_id: "<?= $escaper->escapeUrl($block->getClientId()) ?>",
            }).load(
                {
                    container: "#klarna-kec-placeholder",
                    theme: "<?= $escaper->escapeUrl($block->getTheme()) ?>",
                    shape: "<?= $escaper->escapeUrl($block->getShape()) ?>",
                    locale: "<?= $escaper->escapeUrl($block->getLocale()) ?>",
                    on_click: (authorize) => {
                        require(
                            [
                                'mage/storage',
                                'mage/url',
                                'jquery',
                                'mage/validation'
                            ], function (storage, urlBuilder, $) {
                                var idContent = $('#product_addtocart_form');
                                if (!idContent.valid()) {
                                    return;
                                }

                                var elements = idContent[0];
                                var form = new FormData(elements);
                                var additionalInput = {
                                    'use_existing_quote': 0
                                }

                                additionalInput['auth_callback_token'] =
                                    '<?= $escaper->escapeUrl($authCallbackToken) ?>';

                                form.set('additional_input', JSON.stringify(additionalInput));

                                $.ajax({
                                    url: urlBuilder.build("checkout/klarna/getPayLoad"),
                                    data: form,
                                    type: 'post',
                                    dataType: 'json',
                                    cache: false,
                                    contentType: false,
                                    processData: false,

                                    success: function (result) {
                                        authorize(
                                            {
                                                collect_shipping_address: true,
                                                auto_finalize: false
                                            },
                                            result,
                                            (klarnaResult) => {
                                                require(['Klarna_Kec/js/action/workflow'], function (kec_workflow) {
                                                    kec_workflow(klarnaResult, form);
                                                });
                                            }
                                        );
                                    }
                                });
                            },
                        );
                    }
                }
            );
        };
    </script>
    <script>
        const shadowHost = document.querySelector('#klarna-kec-placeholder');
        const shadowRoot = shadowHost.attachShadow({ mode: 'open' });

        const style = document.createElement('style');
        style.textContent = `
            #klarna-express-checkout {
                width: 100% !important;
            }
        `;

        shadowRoot.appendChild(style);
    </script>
    <style>
        #klarna-kec-placeholder {
            width: 100%;
        }
        @media screen and (min-width: 768px) {
            @media (min-width: 769px) {
                #klarna-kec-placeholder {
                    margin-right: 1%;
                    width: 49%;
                }
            }
        }
    </style>
<?php endif ?>
