<?php
/**
 * Copyright © Klarna Bank AB (publ)
 *
 * For the full copyright and license information, please view the NOTICE
 * and LICENSE files that were distributed with this source code.
 */

/** @var Klarna\Kec\Block\Footer $block */
/** @var Magento\Framework\Escaper $escaper */

if ($block->isKecEnabled()): ?>
    <script src="<?= $escaper->escapeUrl($block->getJsUrl()) ?>" async></script>
<?php endif ?>
